.gitignore, README.md, package-lock.json, package.json, public/index.html, src/App.js, src/components/common/button/Button.jsx, src/components/common/input/Input.jsx, src/index.js, src/pages/Login.jsx, src/pages/Welcome.jsx, src/router/Router.jsx
=> 🌼 init: 프로젝트 초기 세팅

src/pages/Login.jsx
=> ✨로그인 기능 추가

package-lock.json, package.json, src/styles/GlobalStyles.js, src/styles/font.css
🌼 init: styled_components/reset/font적용
closes #6
=> 🌼 init: styled_components/reset/font적용

src/assets/icons/icon-arrow-left.svg, src/components/header/BasicHeader.jsx, src/pages/Home.jsx, src/pages/Login.jsx, src/router/AppRouters.jsx, src/styles/font.css
✨ feat: hhome 파일 경로 수정 차 commit
=> ✨ feat: hhome 파일 경로 수정 차 commit

package-lock.json, package.json
231022_1420
⚙️ ci:recoil, recoilPersist 설치
=> ⚙️ ci:recoil, recoilPersist 설치

src/api/Post/GetFollowerFeedListAPI.jsx, src/components/empty/Empty.jsx, src/index.js, src/pages/Home.jsx, src/pages/Login.jsx, src/recoil/accountname.js, src/recoil/loginCheck.js, src/recoil/loginToken.js
231022_2020
✨ feat:  팔로잉 피드 리스트 존재유무 기능 추가
=> ✨ feat:  팔로잉 피드 리스트 존재유무 기능 추가

src/assets/icons/x.svg, src/components/header/BasicHeader.jsx, src/components/header/MainHeader.jsx, src/components/header/MoreList.jsx, src/components/header/SearchHeader.jsx, src/styles/HeaderStyled.js
=> ✨ feat: header 모달기능 추가 close #25

src/components/Gathering/GatheringItems.jsx, src/components/Gathering/GatheringList.jsx, src/pages/Gathering.jsx, src/styles/GatheringStyled.js
기존 모임페이지의 레이아웃을 다른 페이지와 일관성 있도록 코드 수정
=> 🎨 style: gathering page 레이아웃 수정

src/components/header/BasicHeader.jsx, src/styles/HeaderStyled.js
UploadHeader 버튼 디자인 수정 및 BasicHeader 경로 및 주석 추가.
=> 🎨 style:UploadHeader 버튼 디자인 수정 close #49

src/api/product/ProductDetailAPI.jsx, src/components/footer/Footer.jsx, src/components/header/UploadHeader.jsx, src/pages/product/ProductAdd.jsx, src/pages/product/ProductDetail.jsx, src/pages/product/ProductList.jsx, src/router/AppRouters.jsx
231025_2300
✨ feat: 상품 상세보기 추가
closes #54
=> ✨ feat: 상품 상세보기 추가

src/components/footer/Footer.jsx, src/styles/EmptyStyled.js, src/styles/LayoutStyled.js
231026_1145
🎨 style: 푸터 하단 고정, LayoutStyle 최소 높이 800px으로 수정
=> 🎨 style: 푸터 하단 고정, LayoutStyle 최소 높이 800px으로 수정

src/components/header/BasicHeader.jsx, src/components/header/MainHeader.jsx, src/components/header/MoreList.jsx, src/components/header/SearchHeader.jsx, src/components/header/UploadHeader.jsx, src/styles/HeaderStyled.js
🎨 style: header 메뉴 스타일 변경
z-index 수정 및 margin-bottom 5px > 10px로 변경
✨ feat: 모달창 열리면 스크롤 잠금 기능 추가 
MoreList.jsx
openModal > useEffect() 사용하여 body.style.overflow를 변경하는 코드 추가.
=> Feature/header ScrollLock 기능 추가 및 헤더 메뉴 스타일 수정.

src/pages/profile/Profile.jsx
header, footer 삽입 완료
css 디테일 수정 완료
프로필 이미지 기능 완료
그리드 형식일때 그림 누르면 모달창으로 뜨게 하기
내 프로필 UI 구현 완료
- 이유
- 작업 내역 
- 동작 
- 특이 사항
close: #
=> ✨ feat:: footer/header 추가, 프로필 이미지 완료, 내 프로필 UI 구현 완료

src/pages/Welcome.jsx, src/styles/LoginStyled.js, src/styles/WelcomeStyled.js
- 이유
- Splash 화면 UI 구현
- 로그인 상태 확인 => 3초 뒤 로그인 상태가 true라면 home / false인 경우 login으로 이동
- 동작 
- 특이 사항
close: #70
=> ✨ feat: 웰컴 페이지 UI 구현,  3초 뒤 로그인 또는 홈으로 이동 기능 완료 #70

src/api/product/ProductModifyAPI.jsx, src/assets/icons/icon-delete.svg, src/components/modal/CommonModal.jsx, src/pages/Home.jsx, src/pages/product/ProductList.jsx, src/pages/product/ProductModify.jsx, src/styles/ModalStyled.js
- 본인이 올린 상품에 대한 수정 기능 개발
- Header 컴포넌트 저장 버튼을 누르면 수정한 데이터를 API 를 통해 수정 내역 저장
- 
- 특이 사항
close: #73
=> ✨ feat:: 상품 수정 기능 추가

src/pages/profile/GreedFeed.jsx, src/pages/profile/ListFeed.jsx, src/pages/profile/MyProfile.jsx
- 이유
- 작업 내역 프로필/my 프로필 분리,  리스트 피드/그리드 피드 분리
- 동작 
- 특이 사항
close: #
=> ✏️ Rename : 피드 부분 파일 모듈화, 프로필my 프로필 분리

src/api/profile/FollowAPI.jsx, src/api/profile/FollowerListAPI.jsx, src/api/profile/FollowingListAPI.jsx, src/api/profile/UnFollowAPI.jsx, src/components/profile/FollowItems.jsx, src/pages/profile/Followers.jsx, src/pages/profile/Followings.jsx, src/router/AppRouters.jsx, src/styles/FollowStyled.js
- 로그인한 유저의 팔로잉/ 팔로우 목록 UI로 구현
- 이유
- 작업 내역 
- 로그인 한 토큰 확인하여 팔로잉 및 팔로워 리스트 구현
- page : /profile/followings
- 동작 
- 특이 사항
close: #76
=> ✨ feat: 팔로잉/ 팔로워 목록 UI 및 기능 구현

src/api/EditProfileApi.jsx, src/pages/Join.jsx, src/pages/profile/EditProfile.jsx, src/pages/profile/SetProfile.jsx, src/router/AppRouters.jsx, src/styles/JoinStyled.js, src/styles/SetProfileStyled.js
- 이유
- 프로필 수정 페이지 UI 구현
- API로 데이터 받아온 후 input value에 삽입
- 새로운 값 저장 후 다시 API로 전송
- 동작 
- 특이 사항
close: #72
=> 프로필 수정 페이지 UI 구현, 기능 구현

src/components/profile/MyProduct.jsx, src/components/profile/MyProductItems.jsx, src/styles/MyProductStyled.js
- 이유
- 게시자가 올린 글을 따로 확인할 수 있는 컴포넌트 제작
- 작업 내역 
- 프로필 화면과 피드 사이에 상품 리스트 구현
- 특이 사항
close: #84
=> ✨ feat: 프로필 내 상품 리스트 구현 #84

src/api/Post/GetFollowerFeedListAPI.jsx, src/api/Post/MyFeedListAPI.jsx, src/pages/profile/GreedFeed.jsx, src/pages/profile/ListFeed.jsx, src/pages/profile/MyProfile.jsx, src/pages/profile/Profile.jsx
- 이유
- 작업 내역 프로필 api와 피드 연결, product 연결 
- 동작 
- 특이 사항
close: #
=> ✨ feat:  api와 피드 연결 완료, product 연결 완료

src/api/profile/ProfileInfoAPI.jsx, src/components/common/button/Button.jsx, src/components/empty/Empty.jsx, src/components/footer/Footer.jsx, src/pages/Login.jsx, src/pages/profile/EditProfile.jsx, src/pages/profile/ListFeed.jsx, src/pages/profile/Profile.jsx, src/recoil/loginCheck.js, src/recoil/loginToken.js, src/styles/EmptyStyled.js, src/styles/GlobalStyles.js, src/styles/JoinStyled.js
- 메인 폰트, 메인 컬러 미적용 부분 적용
- 작업 시 로컬 스토리지 사용으로 인한 세션 스토리지 주석 처리
- 버튼 컴포넌트 폰트 적용, active 시 색 변경
- footer 아이콘 사이즈, 폰트 수정, 색 수정
- home 화면 empty 로고, 버튼 크기 수정
- feed 글 line-height 조정
- 메인 컬러 변수 처리
- 프로필 팔로우 버튼 색상 변경
- localStorage 사용 부분 sessionStorage 코드 주석으로 추가
- 특이 사항
close: #
=> 🎨 style: 세션 스토리지 주석 처리, css 코드 수정

src/api/Post/GetFollowerFeedListAPI.jsx, src/api/Post/PostDetailAPI.jsx, src/api/Post/PostModifyAPI.jsx, src/components/footer/Footer.jsx, src/components/modal/CommonModal.jsx, src/pages/Home.jsx, src/pages/post/PostDetail.jsx, src/pages/post/PostModify.jsx, src/pages/post/PostUpload.jsx, src/pages/product/ProductDetail.jsx, src/router/AppRouters.jsx
- 피드 전체적인 기능 개발 필요
- 팔로워 유저 게시물 리스트 조회, 상세조회, 수정 기능 개발
- 동작 
-
- 특이 사항
close: #79
=> ✨ feat:  팔로워피드조회, 상세조회, 수정 기능 개발완료

src/api/Post/PostDeleteAPI.jsx, src/api/product/ProductDeleteAPI.jsx, src/components/empty/Empty.jsx, src/components/footer/Footer.jsx, src/components/modal/CommonModal.jsx, src/pages/Home.jsx, src/pages/post/PostDetail.jsx, src/pages/product/ProductDetail.jsx, src/pages/product/ProductList.jsx, src/styles/HeaderStyled.js
- 삭제 기능 필요
- 피드 삭제, 게시물 삭제 API 및 모달 삭제 버튼 개발
- 
- 특이 사항
close: #90
=> ✨ feat:  피드, 상품 삭제 기능 완료

src/api/profile/FollowerListAPI.jsx, src/api/profile/FollowingListAPI.jsx, src/components/profile/FollowItems.jsx, src/pages/profile/Followers.jsx, src/pages/profile/Followings.jsx, src/router/AppRouters.jsx
- 이유 : 기존 팔로잉/팔로우 페이지는 로그인한 accountname을 기준으로 데이터를 가지고 오고 있었음. 이를 해당 페이지의 accountName을 가지고 오는 것으로 변경
- api 변경
- 해당 accountname 비교하여 본인 계정인지 확인
- 팔로잉 유무에 따른 버튼 변화
- 특이 사항
close: #92
=> ✨ feat : 팔로잉/팔로워 페이지 API 변경 #92

src/components/profile/MyProduct.jsx, src/styles/MyProductStyled.js
- 이유 : 프로필 내 상품이 로그인 API를 사용하고 있어 이를 해당 페이지의 API를 이용하여 상품을 리스트하도록 함.
- 해당 프로필의 API를 이용하여 상품을 렌더링하도록 변경
- 상품리스트의 길이가 길어져 스크롤이 생기면 해당 스크롤 버튼이 생기도록 추가
- 특이 사항
close: #95
=> ✨ feat: 프로필 내 상품 리스트 API 수정 #95

src/api/Post/PostUploadAPI.jsx, src/api/comment/CommentDeleteAPI.jsx, src/api/comment/CommentListAPI.jsx, src/api/comment/CommentUploadAPI.jsx, src/components/comment/Comment.jsx, src/components/comment/CommentInput.jsx, src/components/modal/CommonModal.jsx, src/pages/Home.jsx, src/pages/post/PostDetail.jsx, src/pages/product/ProductAdd.jsx, src/styles/CommentStyled.js, src/styles/HeaderStyled.js, src/styles/LayoutStyled.js, src/styles/ModalStyled.js, src/utils/timeGapCalculator.js
- 피드 댓글 기능 필요
- Comment 관련 API 및 페이지, 컴포넌트 개발
- 
- 특이 사항
close: #98
=> ✨ feat:  피드 댓글 조회/추가/삭제 기능 개발 완료

src/api/SearchApi.jsx, src/components/empty/Empty.jsx, src/components/header/SearchHeader.jsx, src/pages/Search.jsx, src/router/AppRouters.jsx, src/styles/HeaderStyled.js, src/styles/LayoutStyled.js, src/styles/SearchStyled.js
- 이유
- 검색 페이지 UI 구현
- 검색 input 입력 값에 따라 api 통신 => 검색 결과 출력(닉네임, 아이디)
- 특이 사항
close: #97
=> ✨ feat: 검색 페이지 UI 구현, 입력 값에 따라 검색 결과 출력 기능 구현

src/components/header/MainHeader.jsx, src/pages/Home.jsx, src/pages/Search.jsx, src/styles/EmptyStyled.js, src/styles/HeaderStyled.js, src/styles/SearchStyled.js
- 검색/헤더 크기 조정 => 검색 페이지로 넘어가면 헤더 크기가 달라져서 조정
- Empty 높이 조정 => Empty 높이가 100vh로 되어 있어서 스크롤이 생성 됨 header+footer+margin 부분을 뺌
- 검색 시 프로필 이미지도 화면에 출력, 기본 이미지일 시 톡후감 기본 프로필 이미지로 보이게 설정
- 특이 사항
close: #97
=> ✨ feat: 검색 이미지 불러오기,  검색/헤더 크기 조정, Empty 크기 조정

src/api/Post/PostDeleteAPI.jsx, src/assets/icons/icon-edit.svg, src/components/empty/Empty.jsx, src/components/header/MainHeader.jsx, src/components/profile/MyProduct.jsx, src/pages/Home.jsx, src/pages/post/PostDetail.jsx, src/pages/product/ProductDetail.jsx, src/pages/product/ProductList.jsx, src/styles/HeaderStyled.js, src/styles/MyProductStyled.js, src/utils/timeFormat.js
- 홈 헤더/날짜형식변경/홈상품연결개선/기타css변경
- 홈 헤더/날짜형식변경/홈상품연결개선/기타css변경
- 동작 
- 특이 사항
close: #
=> ✨ feat:  홈 헤더/날짜형식변경/홈상품연결개선/기타css변경

src/pages/profile/GreedFeed.jsx, src/pages/profile/ListFeed.jsx, src/pages/profile/Profile.jsx, src/styles/MyProductStyled.js
- 이유내 프로필/유저 프로필 UI 구별, 시간 수정
- 작업 내역 내 프로필/유저 프로필 UI 구별, 시간 수정
- 동작 
- 특이 사항
close: #
=> ✨ feat:  내 프로필/유저 프로필 UI 구별, 시간 수정

src/api/profile/FollowAPI.jsx, src/api/profile/UnFollowAPI.jsx, src/components/profile/BtnFollowing.jsx, src/components/profile/BtnUnFollowing.jsx, src/components/profile/FollowItems.jsx, src/pages/profile/Followers.jsx, src/pages/profile/Followings.jsx
- 이유
- 버튼 눌렀을 때 팔로잉 / 언팔로잉 기능 구현
- 작업 내역 
- 불필요한 코드 삭제 및 팔로잉 / 언팔로잉 기능 추가
- 동작 
- 팔로잉 버튼 누를 시 해당 프로필의 어카운트네임을 기반으로 로그인한 계정의 팔로잉에 추가
- 언팔로잉 버튼을 누를 시 로그인한 계정의 팔로잉 리스트에서 해당 계정 삭제.
- 특이 사항
close: #108
=> ✨ feat: 팔로잉 / 언팔로잉 기능 구현 #108

src/styles/ModalStyled.js, src/styles/MyProductStyled.js
- [] 신규 기능 추가 :
- [x ] 기타 : 폰트 미적용 이슈 수정
- 게시물 작성 -> 상품 등록/피드 등록 메인 폰트 미적용
- 프로필 -> 판매중인 상품 -> 내용 부분 메인 폰트 미적용
- 해당 스타일에 폰트 적용
- 동작 
- 특이 사항
close: #110
=> 🎨 style : 폰트 수정 #110

src/api/product/ProductDeleteAPI.jsx, src/api/product/ProductUploadAPI.jsx, src/components/common/LikeHeart.jsx, src/pages/Home.jsx, src/pages/post/PostDetail.jsx, src/pages/product/ProductList.jsx, src/styles/CommentStyled.js
- 좋아요 클릭시 모든 게시물 색상 변경됨
- 좋아요 컴포넌트 제작 및 소스 변경
- 선택한 아이콘만 변경
- 특이 사항
close: #
=> 🎨 style: 좋아요 아이콘 클릭시 선택한 부분만 색상변경 컴포넌트 제작

src/api/Post/PostHeartAPi.jsx, src/api/Post/PostUnHeartAPI.jsx, src/components/profile/LikeHeart.jsx
- 게시글 내 사용할 수 있는 좋아요 Component 추가
- 좋아요 api , 좋아요 취소 api 제작
- 이를 사용하는 좋아요 버튼 구현
- 하트를 누르면 좋아요 상태에 따라 작동
- 특이 사항
close: #114
=> ✨ feat: 좋아요 기능 #114

src/api/product/ProductUploadAPI.jsx, src/components/comment/Comment.jsx, src/components/comment/CommentInput.jsx, src/components/modal/PostInsertModal.jsx, src/pages/Home.jsx, src/pages/post/PostDetail.jsx, src/pages/product/ProductAdd.jsx, src/pages/product/ProductDetail.jsx, src/pages/product/ProductList.jsx, src/pages/product/ProductModify.jsx
- 댓글인풋창초기화, 상품등록화면 개선 필요
- 댓글 무한 렌더링 코드 수정, 상품 내용 등록시 Enter 적용 및 UI 개선
- 
- 특이 사항
close: #
=> ✨ feat:  댓글입력창/상품입력화면/기타 UI 개선

src/pages/profile/ListFeed.jsx
- 이유 하트 수정, 전체적인 프로필 수정 완료
- 작업 내역 하트 수정, 전체적인 프로필 수정 완료
- 동작  
- 특이 사항
close: #
=> ✨ feat: 하트 수정, 전체적인 프로필 수정 완료

src/assets/icons/s-icon-more-vertical.svg, src/components/header/BasicHeader.jsx, src/components/header/MainHeader.jsx
- [] 신규 기능 추가 :
---
- 마크업 준수를 위해 Header 안에 `<h1 className="a11y-hidden">톡후감</h1>` 추가
- Basic Header에 페이지 이름 추가
---
---
- 마크업 준수를 위해 Header 안에 `<h1 className="a11y-hidden">톡후감</h1>` 추가
- Basic Header에 페이지 이름 추가
- 더보기 메뉴 아이콘의 색상을 더 진하게 변경
---
등등
- 페이지 별 이름 및 링크 혹은 헤더 연결은 추후 의논을 통해 수정 필요.
- 마크업 준수를 위한 의논 필요.
- 헤더를 구현하는 방법을 변경하는 방법은 어떤지 이야기 해보는 것도 좋을 것 같음. 
- ex) 헤더가 필요한 모든 페이지에 `basicHeader.jsx`를 넣고   `location.pathname`에 따른 `return값`을 다르게 하는 방법이 나을지 아니면 그냥 이대로 진행하는 것이 나을지.
- #57
=> 🎨 style: 헤더 pageName 및 더보기 이미지 색상 변경. #57

README.md
=> 리드미 이미지 확인

src/pages/profile/ListFeed.jsx
- 프로필 내 피드에서 API 그대로 받아와지는 부분 수정
- 작업 내역 
- 특이 사항
close: #
=> ✨ feat: 프로필 피드 부분 책 정보 받아오는 부분 수정

README.md
- 📃 docs: Readme 수정
- 📃 docs: Readme
- 동작 
- 특이 사항
close: #
=> 📃 docs: Readme 수정

src/api/Post/PostModifyAPI.jsx, src/pages/post/PostModify.jsx
- 이유
- 책 검색 api 부분과 PostModify.jsx 연결 / textarea 수정 안 되는 버그 해결
- 특이 사항
close: #
=> 🐛 fix: 책 검색 api와 게시물 수정 연동 버그 해결

src/components/header/MoreList.jsx, src/pages/Login.jsx, src/pages/NotFound.jsx, src/router/AppRouters.jsx, src/styles/EmptyStyled.js
- 이유
- 작업 내역 
- 동작 
- 특이 사항
close: #
=> 🐛 fix: 로그인페이지 이동 및 NotFound 에러 해결

src/components/loading/Loading.jsx, src/styles/LodingStyled.js
- 로딩 화면 부분을 보다 직관적이게 변경
- 작업 내역 
- 특이 사항
close: #
=> 🎨 style: 로딩 화면 로딩바 추가

README.md
- 리드미 협업 부분 추가
- 역할 분담 사진 수정
- 작업 내역 
- 동작 
- 특이 사항
close: #
=> 리드미 협업 부분 추가, 역할 분담 사진 수정
